### ISSUE TITLE
This is a message from Google Translate

### ISSUE THREAD

**Issue by xiamuguizhi** [KeenRivals/brashear.me#1]
I am a newbie
I won't have any html css code
I really like the theme of your website.
Can I try to make a typecho theme?

I don't know if you can understand this translation. I don't know English. I am sorry.

我是一名新手,不会 html css 

我很喜欢的你网站主题，美办法我不会写css 和html

我能尝试帮你主题  制作成typecho主题吗？

**Comment by KeenRivals** [comment]
You're welcome to copy my theme. The theme files are in themes/pelican-feather. I eventually intend to release the theme under GPL 3. You may use the theme under that license.

**Comment by xiamuguizhi** [comment]
@KeenRivals Thank you very much for your answer~
